# example profiles.yml file
postgres_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: airflow
      password: airflow
      port: 5432
      dbname: test
      schema: public
      threads: 1